---
version: '3.7'
services:
  web:
    container_name: 'porta_web'
    hostname: 'porta_web'
    build: 
      context: ./image/nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - '/opt/certbot/data:/etc/letsencrypt'
      - './conf/nginx/conf.d:/etc/nginx/conf.d'
      - './conf/nginx/sites.d:/etc/nginx/sites.d'
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './conf/nginx/auth:/etc/nginx/auth'
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'
  nginx-exporter:
    container_name: 'porta_nginx-exporter'
    hostname: 'porta_nginx-exporter'
    image: 'sophos/nginx-vts-exporter:latest'
    expose:
      - 9913
    depends_on:
      - web
    restart: always
    networks:
      - planet-link
    environment:
      - 'NGINX_STATUS=http://porta_web/status/control?cmd=status&group=*'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'
networks:
  planet-link:
    external: true
