---
version: '3.8'
services:
  web:
    container_name: 'porta_web'
    hostname: 'porta_web'
    build: 
      context: ./image/nginx
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    restart: always
    volumes:
      - '/opt/certbot/data:/etc/letsencrypt'
      - './conf/nginx/conf.d:/etc/nginx/conf.d'
      - './conf/nginx/sites.d:/etc/nginx/sites.d'
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './conf/nginx/auth:/etc/nginx/auth'
      - './www:/www'
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'
networks:
  default:
  planet-link:
    external: true

